project_id = "lqwzcichbqxxrbawpejm"

[functions.send-marketing-email]
verify_jwt = false

[functions.cancel-campaign]
verify_jwt = false

[functions.run-scheduled-campaigns]
verify_jwt = false

[functions.sync-emailoctopus]
verify_jwt = false

[functions.validate-referral-code]
verify_jwt = false

[functions.send-referral-invite]
verify_jwt = false

[functions.send-referral-reward-notification]
verify_jwt = false

[functions.update-waitlist-position]
verify_jwt = false

[functions.emailoctopus-webhook]
verify_jwt = false

[functions.add-facebook-lead]
verify_jwt = false
