/**
 * AgentFileOutput
 *
 * Renders files generated by an agent's code execution (charts, CSVs, reports).
 * Drop into: src/components/ai-employees/AgentFileOutput.tsx
 *
 * Usage: parse tool_calls_made from the agent message metadata,
 * or pass files directly from the orchestrator response.
 */

interface AgentFile {
  name: string
  url: string
  type: string
}

interface AgentFileOutputProps {
  files: AgentFile[]
}

export function AgentFileOutput({ files }: AgentFileOutputProps) {
  if (!files || files.length === 0) return null

  return (
    <div className="mt-2 flex flex-col gap-2">
      {files.map((file) => (
        <FileCard key={file.url} file={file} />
      ))}
    </div>
  )
}

function FileCard({ file }: { file: AgentFile }) {
  const isImage = file.type.startsWith("image/")

  if (isImage) {
    return (
      <div className="rounded-lg overflow-hidden border border-border max-w-lg">
        <img
          src={file.url}
          alt={file.name}
          className="w-full object-contain max-h-96"
          loading="lazy"
        />
        <div className="flex items-center justify-between px-3 py-2 bg-muted/50">
          <span className="text-xs text-muted-foreground truncate">{file.name}</span>
          <a
            href={file.url}
            download={file.name}
            target="_blank"
            rel="noopener noreferrer"
            className="text-xs text-primary hover:underline ml-2 shrink-0"
          >
            Download
          </a>
        </div>
      </div>
    )
  }

  return (
    <a
      href={file.url}
      download={file.name}
      target="_blank"
      rel="noopener noreferrer"
      className="flex items-center gap-3 rounded-lg border border-border px-3 py-2.5 hover:bg-muted/50 transition-colors max-w-sm"
    >
      <FileIcon type={file.type} />
      <div className="flex flex-col min-w-0">
        <span className="text-sm font-medium truncate">{file.name}</span>
        <span className="text-xs text-muted-foreground">{friendlyType(file.type)}</span>
      </div>
      <DownloadIcon className="ml-auto h-4 w-4 text-muted-foreground shrink-0" />
    </a>
  )
}

function FileIcon({ type }: { type: string }) {
  const base = "h-8 w-8 rounded flex items-center justify-center text-xs font-bold text-white shrink-0"

  if (type === "text/csv") return <div className={`${base} bg-emerald-500`}>CSV</div>
  if (type.includes("excel") || type.includes("spreadsheet"))
    return <div className={`${base} bg-green-600`}>XLS</div>
  if (type === "application/json") return <div className={`${base} bg-amber-500`}>JSON</div>
  if (type === "text/html") return <div className={`${base} bg-orange-500`}>HTML</div>
  if (type === "application/pdf") return <div className={`${base} bg-red-500`}>PDF</div>
  return <div className={`${base} bg-slate-500`}>FILE</div>
}

function friendlyType(mimeType: string): string {
  const map: Record<string, string> = {
    "text/csv": "CSV Spreadsheet",
    "application/json": "JSON File",
    "text/html": "HTML Report",
    "application/pdf": "PDF Document",
    "text/plain": "Text File",
    "image/png": "PNG Image",
    "image/svg+xml": "SVG Chart",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": "Excel Spreadsheet",
  }
  return map[mimeType] ?? "File"
}

function DownloadIcon({ className }: { className?: string }) {
  return (
    <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
      <path strokeLinecap="round" strokeLinejoin="round" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
    </svg>
  )
}
